wyshlist/wyshlist

app/assets/stylesheets/components/_forms.scss
app/controllers/wishes_controller.rb
app/views/wishes/index.html.erb
app/views/wishlists/index.html.erb

Fix: switched colors in form

---

app/views/wishlists/_form.html.erb
app/views/wishlists/edit.html.erb

Feat: changed wording in edit wishlist

---

app/models/user.rb
app/views/devise/registrations/new.html.erb
app/views/wishes/_wishes.html.erb
app/views/wishes/show.html.erb
app/views/wishlists/index.html.erb
db/migrate/20230505154433_add_name_to_users.rb
db/migrate/20230505154756_switch_email_to_name_in_users.rb
db/schema.rb

Feat: added first_name logic and migration to change existing users

---

app/controllers/organizations_controller.rb
app/views/shared/_navbar.html.erb

Feat: changed controller method

---

app/controllers/application_controller.rb
app/controllers/wishes_controller.rb
app/models/user.rb
app/policies/application_policy.rb
app/policies/wish_policy.rb
app/policies/wishlist_policy.rb
spec/features/wishlists_spec.rb

fixed the pundit logic for accessing a list

---

app/controllers/organizations_controller.rb
app/controllers/wishlists_controller.rb
app/models/organization.rb
app/models/wishlist.rb
app/views/organizations/show.html.erb
app/views/wishes/index.html.erb
app/views/wishlists/_form.html.erb
app/views/wishlists/new.html.erb
db/migrate/20230518095124_add_organization_to_wishlists.rb
db/schema.rb
spec/features/votes_spec.rb
spec/features/wishes_spec.rb
spec/features/wishlists_spec.rb

46 fixing unvalidated tests

---

app/controllers/wishes_controller.rb
app/policies/application_policy.rb
app/views/wishes/edit.html.erb
spec/features/wishes_spec.rb

fixed deslete wish

---

README.md

Added read me v1

---

Gemfile.lock
app/models/user.rb
app/models/wish.rb
config/routes.rb

`has_many :users` on `wish.rb` model needs to be removed

#49 bug on admin show page done

---

app/controllers/pages_controller.rb
app/views/pages/privacy_policy.html.erb
app/views/pages/terms_of_service.html.erb
app/views/shared/_footer.html.erb
config/routes.rb

Added privacy policy and terms

---

app/models/wish.rb
spec/models/wish_spec.rb

60 automatic upvote

---

app/javascript/controllers/clipboard_controller.js
app/javascript/controllers/index.js
app/views/wishes/index.html.erb

90 add stimulus controller for clipboard

---

app/views/wishlists/_form.html.erb

add the organization input on the form

---

app/views/shared/_navbar.html.erb
app/views/wishlists/index.html.erb

112 - Change your feed for your contributions

---

app/views/shared/_navbar.html.erb
app/views/wishlists/index.html.erb

Revert "112 - Change your feed for your contributions"

---

app/controllers/organizations_controller.rb
app/models/wishlist.rb
app/views/layouts/application.html.erb
app/views/organizations/_form.html.erb
app/views/organizations/show.html.erb
app/views/shared/_user_navbar.html.erb
app/views/wishes/index.html.erb
spec/features/wishes_spec.rb

Made organizations show and wishes index white label

---

app/assets/stylesheets/components/_cards.scss
app/views/wishlists/_wishlists_cards.html.erb

Redesigned the baords to be much thinner

---

app/assets/stylesheets/components/_actiontext.scss
app/assets/stylesheets/components/_buttons.scss
app/assets/stylesheets/components/_cards.scss
app/assets/stylesheets/components/_wrappers.scss
app/views/shared/_user_navbar.html.erb
app/views/wishes/index.html.erb

Added new ticket to be visible al the time on the sticky sidebar

---

app/views/shared/_navbar.html.erb

Added public preview button and new navbar links

---

app/controllers/wishlists_controller.rb
app/views/organizations/show.html.erb
app/views/shared/_user_navbar.html.erb
db/schema.rb

fix: adding if-statement to check wishlist on organizations#show

---

config/initializers/rails_admin.rb

fix: change root_path when not authorized

---

Gemfile
spec/factories/comments.rb
spec/factories/organizations.rb
spec/factories/users.rb
spec/factories/wishes.rb
spec/factories/wishlists.rb
spec/rails_helper.rb

134 - Add main factories

---

config/routes.rb

Fixed typo comma

---

config/routes.rb
lib/constraints/subdomain_constraint.rb

remove the doubled organizations#show from routes
close #164

fix: subdomain constraint on organizations#show

---

app/views/devise/registrations/new.html.erb

fix: position of avatar on sign up page

---

app/assets/stylesheets/components/_banner.scss
app/assets/stylesheets/components/_cards.scss
app/assets/stylesheets/components/_navbar.scss
app/assets/stylesheets/components/_wrappers.scss
app/views/layouts/application.html.erb
app/views/pages/components/_how_it_works.html.erb
app/views/pages/home.html.erb
db/schema.rb

[WD-43] - New homepage adjustments

---

app/assets/stylesheets/components/_buttons.scss

[WD-46] - Added button hover on google button

---

app/views/devise/sessions/new.html.erb
app/views/shared/_pages_navbar.html.erb
app/views/wishes/_form.html.erb
app/views/wishes/index.html.erb

[WD99 + WD104 + WD106] add cta create on navbar + armonise CTA colors in preview

---

app/assets/stylesheets/components/_navbar.scss
app/views/shared/_user_navbar.html.erb

Added key to photo url

---

app/controllers/organizations_controller.rb
app/controllers/wishes_controller.rb
app/views/organizations/feedback.html.erb
config/routes.rb

WD-96 Adding prompt when no tickets created

---

app/javascript/controllers/index.js
app/javascript/controllers/modal_pass_value_controller.js
app/views/organizations/feedback.html.erb

Wd 115 dropdown add button

---

Gemfile
Gemfile.lock
app/controllers/organizations_controller.rb
app/services/subdomain_creator.rb

Now the subdomains are created in Heroku, it should fix the 404 error, we might need to add subdomains to all existing organizations in productions as well

Added sudmoain creator service for new subdomains

---

app/assets/stylesheets/components/_forms.scss
app/views/shared/_pages_navbar.html.erb

bigger logo

---

app/controllers/application_controller.rb
app/views/shared/_user_navbar.html.erb

Navbar now alligned and not dependent on @wishlist

Reset scope for navbar

---

app/controllers/organizations_controller.rb
app/policies/organization_policy.rb
app/views/organizations/boards.html.erb
app/views/shared/_dashboard_navbar.html.erb
app/views/shared/_navbar.html.erb
config/routes.rb

Should picked up the navbar once branch #204 is merged

Wd 114 wishlists view

---

app/assets/stylesheets/components/_cards.scss
app/models/comment.rb
app/views/wishes/show.html.erb

add visual cue for staff comments

---

app/assets/stylesheets/components/_forms.scss
app/views/integrations/new.html.erb
app/views/organizations/feedback.html.erb
app/views/shared/_dashboard_navbar.html.erb
app/views/shared/_user_navbar.html.erb
app/views/wishlists/_form.html.erb
app/views/wishlists/new.html.erb

Changed wordings of wishlist to boards

---

app/assets/stylesheets/components/_cards.scss
app/controllers/organizations_controller.rb
app/controllers/wishes_controller.rb
app/policies/application_policy.rb
app/policies/wish_policy.rb
app/views/organizations/feedback.html.erb
app/views/wishes/_form.html.erb
app/views/wishes/_ticket.html.erb
app/views/wishes/show.html.erb

Cleaned up a lot of things and fixed the buttons. now we jus tneed to wrap the edit form with the dashboard view.

Fixed the preloading of a ticket

---

app/assets/stylesheets/components/_forms.scss
app/views/devise/registrations/edit.html.erb
app/views/organizations/_form.html.erb
app/views/organizations/edit.html.erb

Wd 143 move all forms to left

---

app/controllers/application_controller.rb
app/controllers/passthrough_controller.rb
app/views/wishes/show.html.erb

Fixed onboarding for end user to not be redirected to new organization

---

Gemfile.lock
app/assets/stylesheets/components/_buttons.scss
app/assets/stylesheets/components/_forms.scss
app/views/wishes/show.html.erb

[WD-124] fix height comment box

---

app/assets/stylesheets/components/_wrappers.scss
app/assets/stylesheets/config/_colors.scss

[WD-153]  style: update filter color to grey

---

Gemfile.lock
app/assets/stylesheets/components/_forms.scss
app/controllers/wishlists_controller.rb
app/javascript/controllers/character_counter_controller.js
app/javascript/controllers/index.js
app/models/wishlist.rb
app/views/shared/_user_navbar.html.erb
app/views/wishlists/_form.html.erb

[WD-169] Add validation on wishlist title and truncate on dropdown + charcter counter 

---

Gemfile.lock
app/assets/stylesheets/components/_cards.scss
app/models/wish.rb
app/views/wishes/show.html.erb

[WD-170] update bg-color on status comment

---

Gemfile.lock
app/assets/stylesheets/components/_sidebar.scss
app/views/shared/_dashboard_navbar.html.erb
app/views/shared/_nav_links.html.erb
app/views/shared/_sidebar.html.erb
app/views/shared/_sidebar_links.html.erb

First Version of responsive navbar and sidebar 😄

[WD-157] feat: responsive sidebar on dashboard

---

app/controllers/wishlists_controller.rb
app/views/wishes/index.html.erb
spec/models/wish_spec.rb

[WD-176] Added wishlist edit on board page when team memeber
